// <auto-generated />
using Fluent_Video_Player.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("Fluent_Video_Player.Database.FileData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Path");

                    b.Property<float>("Position");

                    b.Property<int>("Views");

                    b.HasKey("Id");

                    b.ToTable("FileDatas");
                });

            modelBuilder.Entity("Fluent_Video_Player.Database.PlaylistData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Playlist");

                    b.HasKey("Id");

                    b.ToTable("PlaylistDatas");
                });

            modelBuilder.Entity("Fluent_Video_Player.Database.PlaylistFileData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Path");

                    b.Property<string>("Playlist");

                    b.HasKey("Id");

                    b.ToTable("PlaylistFileDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
